export const
  TOP        = 'top',
  BOTTOM     = 'bottom',
  UP         = 'up',
  DOWN       = 'down',
  LEFT       = 'left',
  RIGHT      = 'right',
  CENTER     = 'center',
  MIDDLE     = 'middle',
  HEIGHT     = 'height',
  WIDTH      = 'width',
  VERTICAL   = 'vertical',
  HORIZONTAL = 'horizontal',
  HALF       = 'half',
  SHRINK     = 'shrink'
