export const NAME_MAPPING = {
  black: '   noir',
  red: '  rouge',
  green: '   vert',
  yellow: '  jaune',
  blue: '   bleu',
  magenta: '  magen',
  cyan: '   cyan',
  white: '  blanc',
  grey: '   gris',
  bright_black: ' b-noir',
  bright_red: 'b-rouge',
  bright_green: ' b-vert',
  bright_yellow: 'b-jaune',
  bright_blue: ' b-bleu',
  bright_magenta: 'b-magen',
  bright_cyan: ' b-cyan',
  bright_white: 'b-blanc',
  bright_grey: ' b-gris',
}