export { assignMode, assignModeFrom } from './src/assignMode'
export { modeToSgra }                 from './src/modeToSgra'
export { modeToSign }                 from './src/modeToSign'
export { styleToMode }                from './src/styleToMode'
export { signToMode }                 from './src/signToMode'