export { assignMode, assignModeFrom } from './src/assignMode.js'
export { modeToSgra }                 from './src/modeToSgra.js'
export { modeToSign }                 from './src/modeToSign.js'
export { styleToMode }                from './src/styleToMode.js'
export { signToMode }                 from './src/signToMode.js'